In [12]:
import numpy as np
import pandas as pd
import sklearn as skl
from sklearn import datasets 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

Loading and viewing datasets

In [2]:
bh = datasets.load_boston()
print (bh.DESCR)

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

Feature Matrix

In [3]:
# Create feature matrix
X = bh.data

# Create target vector
y = bh.target

print (X)

# convert values as floats
np.set_printoptions(formatter={'float':'{:g}'.format})
print (X.shape)
print (y.shape)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
(506, 13)
(506,)


In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y)
print (X_train.shape)
print (y_train.shape)
print (X_test.shape)
print (y_test.shape)

(379, 13)
(379,)
(127, 13)
(127,)


In [5]:
mymodel = LinearRegression()

In [6]:
mymodel.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

Printing trained model

In [7]:
# check that the coeffients are the expected ones.
m = mymodel.coef_[0]
b = mymodel.intercept_
print(' y = {0} * x + {1}'.format(m, b))

 y = -0.10989802727510788 * x + 41.45405732376395


In [8]:
# predict
ynew = mymodel.predict(X_test)

In [10]:
# The mean squared error
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, ynew))

Mean squared error: 25.67
